### PR TITLE
Added Ren, XBP, 0xBTC, Atom, Elec, MFT,  XLM, IOP

### PR DESCRIPTION
**Pull request by Paulsky**
In sync with last commit of atomiclabs/cryptocurrency-icons [1eff69d935dc0e5a7c5890a2d738bece9556d665](https://github.com/atomiclabs/cryptocurrency-icons/commit/1eff69d935dc0e5a7c5890a2d738bece9556d665).

### CODE REVIEW

**Comment by mirgj** [comment]
@Paulsky great thanks for the contribution will merge this and release a new version soon!

**Comment by Paulsky** [comment]
@mirgj sounds great! Thank you in advance!

**Comment by mirgj** [comment]
@Paulsky just merged and published! Thanks again for the contribution

**Comment by Paulsky** [comment]
Thank you @mirgj! 🙏

**Pull request merged**
